/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "primary-fixed": "#e1e0ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "outline": "#767586",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#fffbff",
        "secondary-container": "#bdbefe",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "primary-container": "#6063ee",
        "on-error-container": "#93000a",
        "tertiary-container": "#a36700",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#404178",
        "inverse-surface": "#2d3133",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#13144a",
        "error": "#ba1a1a",
        "secondary": "#575992",
        "on-primary-fixed": "#07006c",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary": "#4648d4",
        "on-surface-variant": "#464554",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary": "#825100",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "surface-tint": "#494bd6",
        "inverse-primary": "#c0c1ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "outline-variant": "#c7c4d7",
        "secondary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-container": "#494b83"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
